name: service-account
on:
  push: { branches: [main], paths: ['service-account/**'] }
  pull_request: { paths: ['service-account/**'] }
permissions: { contents: read, packages: write, id-token: write }
jobs:
  pipeline:
    uses: shashax42/nebula-ci-templates/.github/workflows/service-pipeline.yml@v1
    with: { service: service-account, run-tests: false }
    secrets: inherit
